spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_work?serverTimezone=UTC
    password: 123456
    username: root
  jpa:
    show-sql: true
mail:
  from:
    username: 18268733945@139.com
    password: ax123456